{{- if .Values.rasterCommon.authentication.opaExporterFileDownloader.enabled }}
{{- $chartName := include "files-server.name" . -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-envoy
data:
  envoy.yaml: |-
{{ tpl (.Files.Get "config/envoy.yaml") . | indent 4 }}
{{- end }}
