{{- if .Values.rasterCommon.authentication.opaFileDownloader.enabled }}
{{- $chartName := include "files-server.name" . -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-opa
data:
  policy.rego: |-
{{ tpl (.Files.Get "config/policy.rego") . | b64enc | indent 4 }}
{{- end }}
