{{- $releaseName := .Release.Name -}}
{{- $chartName := include "files-server.name" . -}}
{{- $cloudProviderFlavor := include "files-server.cloudProviderFlavor" . -}} 

{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "files-server.environment" . }}
    release: {{ $releaseName }}
    {{- include "files-server.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: TCP
      name: internal
    {{- if .Values.rasterCommon.authentication.opaExporterFileDownloader.enabled }}
    - port: {{ .Values.env.externalPort }}
      targetPort: {{ .Values.envoy.port }}
      protocol: TCP
      name: external
    {{- end }}
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nodePort}}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "files-server.selectorLabels" . | nindent 4 }}
{{- end }}
