{{- $releaseName := .Release.Name -}}
{{- $chartName := include "file-download-server.name" . -}}
{{- $cloudProviderFlavor := include "file-download-server.cloudProviderFlavor" . -}} 
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "file-download-server.environment" . }}
    release: {{ $releaseName }}
    {{- include "file-download-server.labels" . | nindent 4 }}
spec:
{{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
    {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: 30020
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "file-download-server.selectorLabels" . | nindent 4 }}
{{- end }}
