apiVersion: v2
name: files-server
description: A Helm chart for files-server
type: application
version: 2.3.0
appVersion: 2.3.0
dependencies:
  - name: nginx
    version: 2.1.5
    repository: oci://acrarolibotnonprod.azurecr.io/helm/common
