global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 30
nodePort: 30030 #for minikube deployment only
splunkIndex: ""
cloudProvider:
  dockerRegistryUrl: acrarolibotnonprod.azurecr.io
  imagePullSecretName: acr-registry
  flavor: openshift

image:
  repository: mc-file-download-server
  tag: V1.0.0-3-gce917d7
storage:
  accessModes: ReadWriteOnce
  storageSize: 5Gi
  storageClass: azure-file
  pv:
    enabled: false
    hostPath: /raster/gpkgs
  internalPvc:
    enabled: false
    name: internal-pvc
  gpkgsPvc:
    enabled: false
    name: gpkgs-storage

env:
  port: 80
  targetPort: 8080
  protocol: TCP
  
resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi