global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: ""
  serviceUrls: {}
  authentication:
    jwtPublicKeySecretName: map-colonies-jwks
  storage:
    gpkgProvider: ""
    fs:
      internalPvc:
        enabled: false
        name: ""
        gpkgSubPath: ""
  ingress:
    domain: "example.com"

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 30
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: true
splunkIndex: ""

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  imagePullSecretName: pullSecretName
  flavor: openshift

serviceUrls:
  ngnixS3Gateway: ""

storage:
  gpkgProvider: ""
  fs:
    internalPvc:
      enabled: false
      name: ""
      gpkgSubPath: ""
authentication:
  opa:
    enabled: false
    customHeaderName: ""

# add pod annotations
# example:
# podAnnotations:
# annotation1: annotation-value-1
# annotation2: annotation-value-2
podAnnotations: {}

env:
  port: 80
  targetPort: 8080
  externalPort: 8080
  protocol: TCP
  tracing:
    url: http://localhost:55681/v1/trace

nginx:
  enabled: true
  fullnameOverride: ""
  authorization:
    enabled: false
  replicaCount: 1
  image:
    repository: nginx-otel-unprivileged
    tag: "v1.0.0"
  port: 8080
  internalServicePort: 80
  targetPort: 8080
  nodePort: 30003

  extraVolumes:
    - name: nginx-config
      configMap:
        name: "{{ .Release.Name }}-files-server-nginx-configmap"
    - name: gpkgs-storage
      persistentVolumeClaim:
        claimName: "internal-pvc-nfs"

  extraVolumeMounts:
    - mountPath: "/etc/nginx/nginx.conf"
      name: nginx-config
      subPath: nginx.conf
    - name: gpkgs-storage
      mountPath: /usr/share/nginx/html/downloads
      subPath: gpkgs

  resources:
    enabled: true
    value:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  route:
    enabled: false
    routesMapping:
      - path: /
        host:
    timeout:
      enabled: false # defaults to 30s by openshift
      duration: 60s # supported units (us, ms, s, m, h, d)
    tls:
      enabled: false
      useCerts: false
      certificate: ""
      key: ""
      caCertificate: ""
  ingress:
    enabled: false
    type: "nginx-org" # supported values: 'nginx-org' | 'nginx-kubernetes
    path: /
    host: ""
    tls:
      enabled: false
      useExternal: ""
    cors:
      enabled: true
      origin: "*"
