global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}
  authentication:
    jwtPublicKeySecretName: map-colonies-jwks

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 30
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: true
splunkIndex: ""
cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  imagePullSecretName: pullSecretName
  flavor: openshift

rasterCommon:
  storage:
    gpkgProvider: FS
    fs:
      internalPvc:
        enabled: true
        name: gpkgs-storage
        gpkgSubPath: gpkgs
  authentication:
    opa:
      enabled: true
      customHeaderName: "x-api-key"

image:
  repository: files-server
  tag: latest

opa:
  image: openpolicyagent/opa
  imageTag: 0.29.4-envoy-3
  port: 9191
  enableLogging: false
  resources:
    enabled: true
    value:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
envoy:
  image: envoyproxy/envoy
  imageTag: v1.20.7
  port: 8000
  maxRequestBytes: 8192
  requestedDomain: rasterExport
  resources:
    enabled: true
    value:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

env:
  port: 80
  targetPort: 8080
  externalPort: 8080
  protocol: TCP
  tracing:
    url: http://localhost:55681/v1/trace
resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: false
  path: /
  tls: true

ingress:
  enabled: false
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
